version: "3.7"
services:

  grafana-envoy:
    image: "envoyproxy/envoy-alpine:v1.20.0"
    environment:
      - ENVOY_UID=0
    volumes:
    - ./grafana-envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      grafana_net:
        aliases:
        # - front-proxy
        - ingress
    depends_on:
    - grafana

    # build:
    #   context: .
    #   dockerfile: Dockerfile-grafanaenvoy
    # networks:
    # - grafana_net

    ports:
    - "9000:3000"
    - "9001:8001"
    

  grafana:
    image: "grafana/grafana"

    # build:
    #   context: .
    #   dockerfile: Dockerfile-service
    volumes:
    - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
    - grafana_net
    ports:
    - "9002:3000"




networks:
  grafana_net: {}
