version: "3.7"
services:

  grafana-envoy:
    build:
      context: .
      dockerfile: Dockerfile-grafanaenvoy
    networks:
    - grafana_net
    ports:
    - "9000:3000"
    - "9001:8001"

  grafana:
    images: grafana/grafana

    # build:
    #   context: .
    #   dockerfile: Dockerfile-service
    # volumes:
    # - ./grafana.int:/etc/grafana/grafana.ini
    networks:
    - grafana_net



networks:
  grafana_net: {}
