version: "3.7"
services:

  grafana-envoy:
    build:
      context: .
      dockerfile: Dockerfile-grafanaenvoy
    networks:
    - grafana_net
    ports:
    - "9000:3000"
    - "9001:8001"

  grafana:
    image: "grafana/grafana"

    # build:
    #   context: .
    #   dockerfile: Dockerfile-service
    volumes:
    - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
    - grafana_net
    ports:
    - "9002:3000"




networks:
  grafana_net: {}
